export const More = {
    "LP": {
        party_name: "Labour Party",
        candidate: "Mr. Peter Obi",
        image:"LP.png",
        bio: [
            "DATE OF BIRTH : 19th July 1961",
            "PLACE OF BIRTH: Onitsha, Nigeria",
            "NATIONALITY: Nigerian",
            "MARITAL STATUS: Married with two children"
        ],
        intro: ["Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut sit repudiandae suscipit iste eligendi, impedit vero nemo corrupti distinctio quibusdam aperiam quisquam odio ullam at, deserunt unde sint fugiat minus! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Impedit, sequi maiores dolore perferendis incidunt expedita ratione optio quidem accusamus consequatur aut ad non culpa veniam. Quod similique dolorum reiciendis dicta. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quasi illum praesentium, at perferendis tempore delectus id nihil animi iste molestias et eum sit cum, fugiat eligendi repellat accusamus vel dolores?Lorem ipsum dolor, sit amet consectetur adipisicing elit. At cumque harum natus repellendus cupiditate soluta maxime! Quos at possimus magnam ipsum, cum necessitatibus vero dignissimos expedita autem numquam. Voluptates, veniam. Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis obcaecati debitis recusandae delectus animi tempora a quibusdam, voluptas deserunt autem alias aperiam quisquam placeat! Natus accusamus veritatis nulla ipsum iste."],
        education: [
            "Christ the King College, Onitsha (W.A.S.C.)",
            "University of Nigeria, Nsukka (B.A. Philosophy)",
            "Lagos Business School, Nigeria (Chief Executive Program)",
            "Harvard Business School, Boston, U.S.A. (Mid to Mid Marketing)",
            "Harvard Business School, Boston, U.S.A. (Changing the Game)",
            "London School of Economics (Financial Mgmt/Business Policy)",
            "Columbia Business School, New York, U.S.A. (Marketing Mgmt )",
            "Institute for Management Development, Switzerland (Senior Executive Program)",
            "Institute for Management Development, Switzerland (Break-Through Program for CEOs)",
            "Kellogg Graduate School of Management, U.S.A. (Advanced Executive Program)",
            "Kellogg School of Management U.S.A. (Global Advanced Mgmt Program)",
            "Oxford University: Said Business School, (Advanced Mgmt& Leadership Program)",
            "Cambridge University: George Business School (Advanced Leadership Program)"
        ],
        prev_position: [
            "Governor, Anambra State of Nigeria (2006-2014)",
            "Honorary Special Adviser to the President on Finance (till May, 2015)",
            "Member, Presidential Economic Management Team (till May, 2015)",
            "Vice-Chairman, Nigeria Governors’ Forum (2008-2014)",
            "Chairman, South-East Governors’ Forum (2006-2014)",
            "Former Chairman: Board of Securities and Exchange Commission (SEC)",
            "Former Chairman: Fidelity Bank Plc.",
            "Former Chairman: Guardian Express Mortgage Bank, Ltd.",
            "Former Chairman: Future Views Securities, Ltd.",
            "Former Chairman: Paymaster Nigeria Plc.",
            "Former Chairman: Next International (Nigeria) Ltd",
            "Former Director: Guardian Express Bank Plc.",
            "Former Director: Chams Nigeria Plc.",
            "Former Director: Emerging Capital Ltd",
            "Former Director: Card Centre Plc"
        ],
        member_pa: [
            "Member, Nigerian Economic Summit Group (NESG)",
            "Member, Nigerian Chartered Institute of Bankers",
            "Member, British Institute of Directors (IOD)"
        ],
        member_fg: [
            "In my capacity as the Governor of Anambra State, I served as a member of:",
            "Federal Government Committee on Minimum Wage",
            "Federal Government Committee on Negotiation with Labour on Subsidy",
            "Federal Government Committee on Mass Transit",
            "Federal Government Committee on Natural Resource",
            "National Economic Council Committee on Power Sector Reform",
            "National Economic Council Committee on Sharing of MDGs Funds",
            "National Economic Council Committee on Accurate Data on Nigeria’s Oil Import and Export",
            "Agricultural Transformation Implementation Council",
            "Sub-Committee on Needs Analysis of Public Universities in Nigeria",
            "National Economic Council Review Committee on the Power Sector"
        ],
        awards: [
            "In my capacity as the Governor of Anambra State, I served as a member of:",
            "2015: Golden Jubilee Award from Catholic Diocese of Onitsha for outstanding contribution to quality healthcare delivery in St. Charles Borromeo Hospital in particular and Anambra State in general, on the occasion of the Golden Jubilee celebration of the hospital.",
            "2014: Nigerian Library Association Golden Merit Award for remarkable improvement of libraries in Anambra State, exemplified by our Government’s construction of the Kenneth Dike Digital State Library, remarkable upgrade of the Onitsha Divisional Library, and provision of library facilities in secondary schools across the State.",
            "2014: Champion Newspaper Most Outstanding Igbo Man of the Decade.",
            "2014: The Voice Newspaper (Holand) Achievers Award for Outstanding Example in Leadership and Governance.",
            "2013: Silver Bird Man of the Year (with Governor BabatundeFashola of Lagos State).",
            "2012: Business Hallmark Newspaper Man of the Year.",
            "2012: The Golden Award on Prudence – by the Methodist Church of Nigeria as the Most Financially Prudent Governor in Nigeria.",
            "2012: Leadership and Good Governance Award by The Ezeife Leadership Foundation Award for restoring peace and harmony to Anambra State.",
            "2012: Best Performing Governor on Immunization in South-East Nigeria – by Bill & Melinda Gates Foundation.",
            "2012: Outstanding Financial Planner and Manager – by the Church of Nigeria, Anglican Communion for my resourcefulness and creativity in governance.",
            "2011: Zik Leadership Prize.",
            "2010: ICT Governor of the Year – by the West Africa ICT Development Award.",
            "2009: Champion Newspaper Nigeria’s Most Trustworthy Governor Award.",
            "2009: Thisday Newspaper Most Prudent Governor in Nigeria.",
            "2007: The Sun Newspaper Man of the Year Award."
        ],
        intro_of_const: [
            "He was the first gubernatorial candidate in Nigeria to legally challenge to its logical conclusion, his governorship electoral victory that was denied him. He won in the Courts and reclaimed his mandate.",
            "He was the first Governor in Nigeria to legally challenge his wrongful impeachment and was reinstated by the Courts.",
            "He was the first Governor in Nigeria to seek the interpretation of tenures of Governors when INEC allowed elections to take place in Anambra State when his tenure had not expired; the election already concluded was cancelled and he was allowed to complete his tenure.",
            "He was the first Governor to serve a 2nd term in both the new and old Anambra State, that is, almost 40 years after creation of the State.",
            "He was the first Governor, whilst still in Office, to be appointed a Special Adviser to the President.",
            "He was the first serving Governor to be appointed into the Presidential Economic Management Team.",
            "He was among the first Governors to be honoured with a National Award in 2011, while still in office.",
            "Though the only Governor whose political party was in government in only one State, he was elected Vice-Chairman of the Nigeria Governors’ Forum twice.",
            "Though the only non-PDP Governor in the South-East (made up of 5 States), he was elected by the other 4 PDP Governors as their Chairman for 8 years rather than the usual one year."

        ],
        fund_achiement:[
        "Anambra was the first State to commence Sub-Sovereign Wealth savings, the first of its kind in Sub-Saharan Africa. At a time many other Governors were leaving huge debts, I left the equivalent of $500 million Dollars in investment as well as local and foreign currency, including $156 million in Dollar-denominated bonds.",
        "For the first time in the history of Anambra State, Ambassadors and High Commissioners of notable countries such as United States, Britain, Russia, European Union, South Africa, Belgium, Israel, the Netherlands, Canada, among others, visited the State. Before my tenure, Anambra was practically a pariah state blacklisted by the Diplomatic Corps and international development partners.",
        " Development partners such as UNDP, UNICEF, the World Bank, DFID, the European Union etc., which hitherto were not in Anambra State started working with the State. Anambra was consistently adjudged one of the best states in development partnership and commitment to reforms for good governance.",
        " He was recognised as Best Governor by the Millennium Development Goals Office (OSSAP-MDGs) and the UNDP in the implementation of their programmes in Nigeria.",
        " The Nigerian Debt Management Office (DMO) rated Anambra as the least indebted state in Nigeria. In spite of visible and measurable achievements recorded in various sectors, the State under him did not borrow or raise bonds for her various projects.",
        " The Senate of the Federal Republic of Nigeria rated Anambra State as the most financially stable state in the country.",
        " The State’s ground-breaking return of schools to their original owners – Voluntary Agencies (Churches) on 1st January 2009, and subsequent partnership with the Agencies in Education, saw the State move from 24th position out of 36 States to Number One in National Examination Council (NECO) and West African Examination Council (WAEC) examinations for three consecutive years. This made the World Bank to commission a study, led by the renowned Prof. Paul Collier of Oxford University, on this revolutionary partnership and phenomenal achievement.",
        " The State also entered into strategic partnership with the Churches in the Health sector. This symbiotic relationship resulted in a tremendous boost to health care because of the services offered by health institutions owned by Voluntary Agencies, while the State restored grants to the agencies and made available to them more than 50 million Dollars in various types of support.",
        " Through partnership with the Church in the Health sector, his Government funded the transformation of -: Iyienu Hospital, Ogidi, Our Lady of Lourdes Hospital, Ihiala St Charles Borromeo Hospital, Onitsha, Holy Rosary Hospital, Waterside, Onitsha and St. Joseph Hospital, Adazi-Nnukwu;",
        " His Government also built the Joseph Nwilo Heart Centre in St. Joseph, Adazi-Nnukwu, where heart operations are now being performed.",
        " His Government won the Bill and Melinda Gates Foundation (1 Million dollars) as the best-performing state in immunisation in the South-East. With complementary funding from our Government, they used the money to build 10 Maternal and Child Care Centres across the State, particularly in rural communities, in partnership with the Churches.",
        " The State was the first to procure and distribute more than 30,000 computers to secondary schools, including 22,500 from HP. The Managing Director for Personal Systems Group HP Inc, Mr. FabriceCampoy described the deployment as the biggest of such projects in the Middle-East and Africa.",
        " Anambra State Government provided Microsoft Academies to more than 500 secondary schools, which the Head of Microsoft in Nigeria (Mr. Ken Span) described as the biggest such deployment in Africa so far.",
        " The State provided Internet access to more than 500 secondary schools, which the CEO of Galaxy Backbone (Mr. Gerald Ilukwe) characterized as incomparable to any in the country.",
        " More than 700 buses were provided to secondary schools in the State by our Government.",
        " Boreholes were provided in schools all over the State.",
        " Numerous classrooms were built in all the 177 communities of the State.",
        " As part of the efforts to turn around the economy of the State, a number of companies were attracted to build their facilities in the Anambra State. A case in point is SABMiller, the 2nd largest brewery in the world, which built their first Green Field facility in the State, which is today one of the most successful facilities they operate globally.",
        " A number of other companies followed the SABMiller initiative and were all supported and encouraged under our Government; a good example is INNOSON Motor Manufacturing Company, from which our government bought more than 1,000 vehicles.",
        " Anambra State for the first time started close collaboration with recognized government security agencies (the Police, Army, Navy, Department of State Security, Civil Defence, among others), offering them various types of support including provision of more than 500 security vehicles. The improvement in security was phenomenal, such that the former IG of Police (Abubakar Mohammed) lauded Anambra State for not witnessing any bank robbery in my last three years in office.",
        " To further enhance security, Anambra State provided at least one security vehicle to each of all the 177 communities in the State as well as various organizations such as markets and Churches.",
        " His Administration conceived and built, from scratch, the first state-owned Teaching Hospital, Chukwuemeka Odumegwu-Ojukwu teaching Hospital, Awka.",
        " His Government commenced the planned development of the Igbariam Campus of the ChukwuemekaOdumegwu-Ojukwu University, including the fencing, construction of internal roads, electrification, construction of the Faculty of Law, Auditorium, Administrative Block, Faculty of Agriculture, Management Building, among others).",
        " His Government attracted the World Bank support on erosion – National Erosion and Watershed Management Project (NEWMAP) – to Anambra State.",
        " His Government was the first to do Poverty Mapping in Nigeria, as a guide for the effective implementation of our poverty-alleviation strategies.",
        " His Government, for the first time, undertook the aerial mapping of Awka as well as the production of Structure Plans for Awka Capital Territory, Onitsha and Nnewi.",
        " During his tenure and with his Government’s support, Anambra State became an oil producing State.",
        " He built the first Secretariat Complex to house State Government Ministries that were hitherto scattered around the State.",
        " His government commenced the development of the ‘Three Arms Zone’ comprising Government House/Governor’s Lodge, Legislative Building/Speakers Residence, and Judiciary Building with Chief Judge’s Residence.",
        " By the end of his tenure in 2014, more than twelve (12) health institutions, including two hospitals, had secured accreditation; when we took off in 2006, no health institution in Anambra State was duly accredited.",
        " Anambra State was the first to undergo national peer review, which scrutinised State Governments for good governance, through the State Peer Review Mechanism (SPRM), an initiative of the Nigerian Governors’ Forum in collaboration with the DFID.",
         ]
    },
    "PDP": {
        party_name: "People's Democratic Party",
        candidate: "Atiku Abubakar GCON",
        image:"PDP.png",
        bio: [
            "DATE OF BIRTH : 25 November 1946"
        ],
        intro: ["Atiku Abubakar GCON (born 25 November 1946) is a Nigerian politician and businessman who served as the vice president of Nigeria from 1999 to 2007 during the presidency of Olusegun Obasanjo. He ran as governor of Adamawa State in 1990, 1997 and later, in 1998, being elected before becoming Olusegun Obasanjo's running mate during the 1999 presidential election and re-elected in 2003.Since his entry into politics in 1989, Atiku Abubakar has unsuccessfully contested five times for the Office of President of Nigeria in 1993, 2007, 2011, 2015 and 2019. In 1993, he contested the Social Democratic Party presidential primaries losing to Moshood Abiola and Baba Gana Kingibe. He was a presidential candidate of the Action Congress in the 2007 presidential election coming in third to Umaru Yar'Adua of the PDP and Muhammadu Buhari of the ANPP. He contested the presidential primaries of the People's Democratic Party during the 2011 presidential election losing out to incumbent President Goodluck Jonathan. In 2014, he joined the All Progressives Congress ahead of the 2015 presidential election and contested the presidential primaries losing to Muhammadu Buhari. In 2017, he returned to the Peoples Democratic Party and was the party presidential candidate during the 2019 presidential election, again losing to incumbent President Muhammadu Buhari. In May 2022, he was chosen as the Peoples Democratic Party candidate in the 2023 Nigerian presidential election. His father was opposed to the idea of Western education and tried to keep Atiku Abubakar out of the traditional school system. When the government discovered that Abubakar was not attending mandatory schooling, his father spent a few days in jail until Aisha Kande's mother paid the fine. At the age of eight, Abubakar enrolled in the Jada Primary School, Adamawa. After completing his primary school education in 1960, he was admitted into Adamawa Provincial Secondary School in the same year, alongside 59 other students. He graduated from secondary school in 1965 after he made grade three in the West African Senior School Certificate Examination. Following secondary school, Abubakar studied a short while at the Nigeria Police College in Kaduna. He left the College when he was unable to present an O-Level Mathematics result, and worked briefly as a Tax Officer in the Regional Ministry of Finance, from where he gained admission to the School of Hygiene in Kano in 1966. He graduated with a Diploma in 1967, having served as Interim Student Union President at the school. In 1967 he enrolled for a Law Diploma at the Ahmadu Bello University Institute of Administration, on a scholarship from the regional government. After graduation in 1969, during the Nigerian Civil War, he was employed by the Nigeria Customs Service. In 2021, Abubakar successfully completed and passed his Master's degree in International Relations at Anglia Ruskin University, Cambridge, United Kingdom.        "],
        education: [],
        prev_position: [],
        member_pa: [],
        member_fg: [],
        awards: [],
        intro_of_const: [],
        fund_achiement:[]
    },
    "APC": {
        party_name: "All Preogressive Congress",
        candidate: "ASIWAJU BOLA TINUBU",
        image:"apc.png",
        bio: [
            "DATE OF BIRTH: 29 March 1952 (age 70)",
            "OCCUPATION: Accountant, Politician",
            "MARITAL STATUS: Married"
        ],
        intro: ["Bola Ahmed Tinubu was elected Senator for the Lagos West constituency in Lagos State, Nigeria in 1993, he also was elected governor of Lagos State (1999 – 2007). He is said to be among Nigeria's most successful politicians ever. He is currently the national leader of the ruling party in Nigeria, All Progressive Congress (APC). EARLY LIFE AND BACKGROUND Asiwaju Bola Ahmed Tinubu was born in Lagos, Nigeria to the illustrious Tinubu Family of Lagos State. He attended Richard Daley College, Chicago Illinois, where he earned himself a place in the honors list of the College. He subsequently proceeded to the Chicago State University, Illinois where he obtained a Bachelor’s degree in Business Administration (Accounting and Management). During his undergraduate years, he was honored with the Outstanding Student’s Award, The University Scholar’s Award and the Certificate of Merit in Accounting and Finance. On his arrival in the U.S. in 1975 and with the support of an ever-adoring mother, this courageous youth, faced with an unflinching zeal to succeed, took on such menial jobs as dishwashing, night-guard and cab-driving to see himself through the initial difficulties of school at the Richard Daley College, Chicago, Illinois. The brilliance of this young Nigerian showed in his ability to make the honours’ list of Richard Daley College. He subsequently transferred to the Chicago State University, Illinois, graduating with honours in 1979 and earning a Bachelor’s Degree in Business Administration (Accounting and Management). During his first year in Chicago State University, young Bola was given the rare privilege to partly teach other students of his Faculty remedial tutorial classes. Most of his colleagues and contemporaries at the university attributed their improved grades to his tutorial lectures. Throughout his undergraduate years, young Bola was on the Dean’s List and was honoured with the Outstanding Student’s Award, the University Scholar’s Award and the Certificate of Merit in Accounting and Finance. He was also awarded the prestigious Sumna cum laude for scoring 3.54 out of possible 4.0 GP. With his successful academic profile, young Bola contested and won his first political election as the President of the Accounting Society of the institution in his final year at the University. Upon graduation with honours and several awards, Bola Tinubu cut his professional teeth at the American-based Arthur Anderson, Deloitte Haskins and Sells (now called Deloitte Haskins and Touche) and GTE Service Corporation - the largest Communication and Utility Company in the United States of America. Meanwhile, at Deloitte Haskins and Sells, the young and professional Bola broadened his experience by participating in the auditing and management consultancy services of General Motors, First National Bank of Chicago, Procter and Gamble, International Harvester, GEC and other Fortune 500 firms. CAREER AND LIFE On his return to Nigeria and with his international experience in Financial Management, young Bola joined Mobil Producing Nigeria as a Senior Auditor before he retired as the company’s Treasurer. As pragmatic, charitable, grassroots’ person, Asiwaju Bola Ahmed Tinubu saw communal service as a veritable tool for social development. He never hesitated to serve his community spearheading several financial contributions and fund-raising for community development programmes in Lagos State. He leads Primrose Group, a political action organization pushing for fundamental changes in the politics of Lagos State. Asiwaju Bola Tinubu opted fully for public service in exchange for his lucrative job at Mobil. His first foray into active politics was as a founding member of the defunct Social Democratic Party (SDP). In 1992, he was elected as an Honourable Senator of the Federal Republic Nigeria to represent Lagos West Senatorial District. At the National Assembly, he distinguished himself as the Chairman of the Senate Committee on Banking, Finance, Appropriation and Currency - a foremost committee of the Senate. With the annulment of the June 12, 1993 Nigerian Presidential Election and the consequent fresh militarization of the Nigerian politics, Asiwaju Bola Ahmed Tinubu became a founding member of the famous pro-democracy group, the National Democratic Coalition (NADECO) which, for several years, engaged the military for the very soul of Nigeria. Subsequently, Bola Tinubu suffered many arrests and detention, harassments and constant threats to his life forcing him to flee Nigeria for his personal safety. He, however, did not give up the struggle as he joined NADECO abroad to continue the agitation for a restoration of democratic governance and the rule in the country. In 1998, Asiwaju Bola Ahmed Tinubu returned to Nigeria to heed a call for all Nigerians to join in the National Reconciliation and Development. A year later, he began his two-term public service as an elected Executive Governor of Lagos State on the platform of the Alliance for Democracy (AD). For his excellent performance as the Executive Governor of Lagos State of Nigeria (1999 – 2007), Asiwaju Bola Ahmed Tinubu received several awards. These include Best Governor in Nigeria for Y2000 by the Nigerian-Belgian Chamber of Commerce; Y2002 Best Practices Prize in improving the living environment, awarded by the Federal Ministry of Works and the UN Habitat Group; Y2000 Best Computerized Government in Nigeria Award by the Computer Association of Nigeria. Asiwaju Bola Ahmed Tinubu was conferred with the Honorary Doctor of Law Degree by the Abia State University in recognition of his immense contribution to democracy, good governance and development of Nigeria. He is the proud recipient of numerous other chieftaincy titles and a patron of many professional and social organizations. As an astute political strategist, Asiwaju Bola Ahmed Tinubu survived the massive incursion of the ruling Peoples Democratic Party (PDP) to the South Western States of Nigeria as the lone re-elected Governor of the Alliance for Democracy (AD). This led him on a regular collision course with the PDP-controlled Federal Government, especially on his creation of additional 37 Local Council Development Areas for Lagos States. A Supreme Court judgment in his favour stated that the Mr. Olusegun Obasanjo’s Federal Government should release the seized statutory allocation of the Lagos State Local Government funds. Asiwaju Bola Ahmed Tinubu was actively involved in the creation of the Action Congress (AC) political party as recourse to the decimated Alliance for Democracy (AD). Rallying like minds across the country, he sold sound ideals and programmes on this fresh and new political platform. Within a few months, he transformed this new party as the credible opposition to the PDP in the country. His political career began in 1992, when he was elected to the Nigerian Senate representing the Lagos West constituency in the short-lived Nigerian Third Republic. After the results of the 12 June 1993 presidential elections were annulled, Tinubu became a founding member of the pro-democracy National Democratic Coalition (NADECO), which mobilized support for the restoration of democracy and recognition of the 12 June results. He went into exile in 1994 and returned to the country in 1998 after the death of military dictator Sani Abacha, which ushered in a transition to civilian rule. In the run-up to the 1999 elections, Bola Tinubu was a protégé of Alliance for Democracy (AD) leaders Abraham Adesanya and Ayo Adebanjo. He won the AD primaries for the Lagos State gubernatorial elections in competition with Funsho Williams and Wahab Dosunmu, a former Minister of Works and Housing. In April 1999, he stood for the position of Executive Governor of Lagos State on the AD ticket and was elected. Lagos State governor. When he assumed office in May 1999, Bola Ahmed Tinubu promised 10,000 housing units for the poor. During his eight-year period of office, he made large investments in education in the state. He also initiated new road construction, required to meet the needs of the fast-growing population of the state. The Oloye Tinubu, alongside a new deputy governor, Femi Pedro, won re-election to office as Governor in April 2003. All other states in the South West fell to the People's Democratic Party. He was involved in a struggle with the Federal government over whether Lagos State had the right to create new Local Council Development Areas (LCDAs) to meet the needs of its large population. The controversy led to the Federal government seizing funds meant for local councils in the state. During the later part of his term in office, he was engaged in continuous clashes with PDP powers such as Adeseye Ogunlewe, a former Lagos State senator who became minister of works, and Bode George, southwest chairman of the PDP. Relations between Bola Tinubu and deputy governor Femi Pedro became increasingly tense after Pedro declared his intention to run for the gubernatorial elections. Femi Pedro competed to become the AC candidate for governor in the 2007 elections, but withdrew his name on the eve of the party nomination. He defected to the Labour Party while still keeping his position as deputy governor. Tinubu's tenure as Lagos State Governor ended on 29 May 2007 when Babatunde Fashola of the Action Congress took office. Fashola had been Chief of Staff to Bola Tinubu. Today, the great legacy of Asiwaju Bola Ahmed Tinubu is built on by his successor, Mr. Babatunde Raji Fashola (SAN), who served as his Chief of Staff. Continuation of Tinubu’s outstanding policies makes the present administration of Lagos State an exceptional and the foremost Government in Nigeria. The Jagaban Borgu still marches on in the political landscape of the country, with a resolve to take on any challenging task with positive public to reduce poverty among his people. Following the victory by the People's Democratic Party (PDP) in the April 2007",
         " elections, Bola Tinubu was active in negotiations to bring together the fragmented opposition parties into a 'mega-party capable of challenging the PDP in 2011. In July 2009, he called for implementation of electoral reforms spelled out in the Uwais report to ensure that the 2011 elections would be as free and fair as the elections of 1993 had been. In December 2009 there were reports that Babatunde Fashola and Bola Tinubu had fallen out over the issue of whether Fashola should run for reelection in 2011, with Tinubu said to be supporting the Commissioner for Environment, Muiz Banire. Tinubu formed a new party alongside Muhammadu Buhari a party which was named All Progressive congress (APC). The goal was to build a stronger party to get rid of the ruling party PDP. In 2015 Tinubu's target became a success as APC won the presidential elections and most of the polls across the country. Tinubu is married to Oluremi Tinubu, the current Senator of central Lagos State. His youngest daughter, Abibat Tinubu, graduated from a Music college in Boston, Massachusetts, US in 2013."], 
        education: [],
        prev_position: [],
        member_pa: [],
        member_fg: [],
        awards: [],
        intro_of_const: [],
        fund_achiement:[]
    },
   
}